on:
  push:
    paths: 
      - 'src/FredApi/**'
    branches:
      - main
  workflow_dispatch:
  
env:
  INITIALS: 'tso'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/FredApi'
  DOTNET_VERSION: '3.1.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build the Azure Function package'
      shell: bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet publish --configuration Release --output ./output
        popd
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: function
        path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
    - uses: actions/download-artifact@v2
      with:
        name: function
      
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: '${{ env.INITIALS }}-fredapi-func-dev'
        package: './'
        publish-profile: ${{ secrets.PUBLISHSETTINGS }}
